In [19]:
from torch.nn import RNN, LSTM
from torch import randn, tensor
import torch
from torch.utils import data as data_utils
import pandas as pd
import numpy
from sklearn.model_selection import train_test_split

In [20]:
df = pd.read_csv('creditcard.csv')

In [21]:
df.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0


## Test w/ Random Data

In [22]:
example_rnn = RNN(10, 20, 2, nonlinearity='relu')
example_input = randn(5, 3, 10)
example_h0 = randn(2, 3, 20)
example_output, example_hn = example_rnn(example_input, example_h0)

In [23]:
#example_output

## Test with Actual Data

### Splitting Data

In [24]:
decision_features = df.columns[:-1]
target_feature = df.columns[-1]

In [25]:
X = df[decision_features]
y = df[target_feature]

In [26]:
#example_tensor = Tensor(X)

In [27]:
rnn = RNN(input_size=len(X.columns), hidden_size=2*len(X.columns), nonlinearity='relu')

In [28]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=999)

In [29]:
X_train_values, y_train_values = X_train.to_numpy(), y_train.to_numpy()
X_test_values, y_test_values = X_test.to_numpy(), y_test.to_numpy()

In [32]:
X_test_values

array([[ 4.48970000e+04, -3.04008214e+00, -1.05850908e+00, ...,
         1.04118337e+00, -3.30897408e-01,  6.72690000e+02],
       [ 1.54541000e+05,  2.08708925e+00, -2.49079306e-01, ...,
        -8.28010009e-02, -8.51256818e-02,  1.29000000e+00],
       [ 8.14440000e+04, -4.41048080e+00, -9.48535283e+00, ...,
        -5.21890753e-01,  5.28177295e-01,  2.96584000e+03],
       ...,
       [ 5.63970000e+04, -5.60853518e-01,  2.81800547e-02, ...,
         4.72755104e-02,  1.42226563e-01,  6.99000000e+01],
       [ 1.70844000e+05, -2.68655008e+00,  1.47874161e+00, ...,
        -1.61787037e-01, -1.02853987e-01,  8.90000000e-01],
       [ 2.80460000e+04, -3.80072722e-01,  1.09513397e+00, ...,
         1.55970524e-01,  3.10581539e-01,  1.79000000e+00]])

### Creating Tensors for data (from Numpy arrays)
* Must specify tensor type that EXACTLY matches nympt dtype or error

In [37]:
X_train_tensor, y_train_tensor = tensor(X_train_values), tensor(y_train_values, dtype=torch.int64)

In [39]:
X_test_tensor, y_test_tensor = tensor(X_test_values), tensor(y_test_values, dtype=torch.int64)

In [40]:
X_train_tensor

tensor([[ 1.2383e+05, -2.0191e+00,  1.0956e+00,  ..., -4.9495e-01,
          1.7480e-01,  2.5900e+01],
        [ 8.2650e+03, -2.3115e+00, -1.1115e+00,  ...,  4.8831e-01,
          1.6544e-01,  1.0667e+02],
        [ 1.2135e+05, -1.2917e+00,  1.9870e-01,  ...,  1.6995e-01,
          1.1399e-01,  1.4490e+02],
        ...,
        [ 8.4491e+04,  1.2422e+00, -5.6249e-01,  ...,  9.7237e-02,
          7.3808e-03,  1.0000e+00],
        [ 5.9385e+04,  6.1682e-01, -1.9596e+00,  ...,  2.3052e-02,
          6.1177e-02,  3.1726e+02],
        [ 1.5153e+05,  1.9329e+00, -1.0664e-02,  ..., -1.6403e-02,
         -1.1258e-02,  1.0111e+02]])

In [43]:
y_test_tensor

tensor([0, 0, 0,  ..., 0, 0, 0])

In [52]:
training_tensor = data_utils.TensorDataset(X_train_tensor, y_train_tensor)

In [53]:
testing_tensor = data_utils.TensorDataset(X_test_tensor, y_test_tensor)

### Testing RNN with actual data

In [54]:
credit_rnn = RNN(input_size = len(decision_features), hidden_size = 2*len(decision_features), nonlinearity='relu')

In [55]:
credit_rnn_outcome, final_hidden_layer = credit_rnn(training_tensor)

AttributeError: 'TensorDataset' object has no attribute 'dim'

In [49]:
final_hidden_layer

tensor([[14692.0371,  1187.6243, 14804.3184,   988.6727,  9100.5918,     0.0000,
             0.0000,  7758.6514, 11401.4570,     0.0000,     0.0000, 17221.9590,
             0.0000,     0.0000,     0.0000,     0.0000,     0.0000,     0.0000,
          6564.6821,   127.8405,  7569.9424, 12622.4580,     0.0000,     0.0000,
          2605.4583, 16323.0898,     0.0000,     0.0000, 15091.3652, 16541.7324,
             0.0000, 14767.9990,     0.0000,     0.0000,     0.0000,     0.0000,
             0.0000,   763.0210,     0.0000,     0.0000,     0.0000,  6340.0654,
             0.0000,     0.0000, 10770.5801,     0.0000, 16752.1270,     0.0000,
             0.0000,  9401.8242,     0.0000,    43.8311,     0.0000,     0.0000,
             0.0000,     0.0000,     0.0000,     0.0000,     0.0000, 17682.3398]],
       grad_fn=<SqueezeBackward1>)

In [50]:
credit_rnn_outcome

tensor([[12354.5225,  1334.4510, 13189.2598,  ...,     0.0000,     0.0000,
         14962.5527],
        [    0.0000,   430.4385,     0.0000,  ...,  4435.3535,     0.0000,
             0.0000],
        [11320.2197,  1893.8320, 10252.3984,  ...,     0.0000,     0.0000,
         15257.1016],
        ...,
        [ 7661.5249,   938.5208,  9101.1240,  ...,     0.0000,     0.0000,
         11071.6475],
        [ 4340.3730,   705.6375,  5630.2817,  ...,     0.0000,     0.0000,
          5794.5386],
        [14692.0371,  1187.6243, 14804.3184,  ...,     0.0000,     0.0000,
         17682.3398]], grad_fn=<SqueezeBackward1>)

## Long Short-Term Memory Model

In [ ]:
# lstm = LSTM()